apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-leaf2"
resources:
- ../../../base

patchesStrategicMerge:
- nodeselectors.yaml
- volumes.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: nvue
  files:
  - nvue.yaml
