- set:
    router:
      bgp:
        autonomous-system: 65002
        enable: "on"
        router-id: 192.0.2.2
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: "on"
                redistribute:
                  connected:
                    enable: "on"
            enable: "on"
            peer:
              10.0.0.2:
                remote-as: external
                type: numbered
    platform:
      hostname:
        value: leaf2
    interface:
      lo:
        ip:
          address:
            192.0.2.2/32: {}
        type: loopback
      swp1:
        ip:
          address:
            10.0.0.3/31: {}