---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: switch
spec:
  selector:
    matchLabels:
      node: leaf2
  template:
    metadata:
      labels:
        node: leaf2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - leaf2