apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-leaf1"
resources:
- ../../../base

patchesStrategicMerge:
- nodeselectors.yaml
- volumes.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: interfaces
  files:
  - interfaces.cfg
- name: frr
  files:
  - frr.conf
