apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: "-spine"
resources:
- ../../../base

patchesStrategicMerge:
- nodeselectors.yaml
- volumes.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: sonic
  files:
  - config_db.json
