---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: switch
spec:
  selector:
    matchLabels:
      node: spine
  replicas: 1
  template:
    metadata:
      labels:
        node: spine
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - spine